version: '3.8'

services:
  fastapi:
    build: .
    ports:
     - "8000:8000"
    volumes:
      - ./qr_codes:/myapp/qr_codes # Maps ./qr_codes from your host to /myapp/qr_codes in the container
      - ./:/myapp/
    environment:
      - QR_CODE_DIR=./qr_codes
      - FILL_COLOR=red
      - BACK_COLOR=white
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./qr_codes:/var/www/qr_codes
